# tasks file for ansible-dockerized-bloodbank to start container
- hosts: local
  tasks:
  - name: "Launch database container"
    docker: 
      name : mysql_container
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      env:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: Bookstore
        MYSQL_USER : user
        MYSQL_PASSWORD: pass
      ports:
        - "32795:3306"
      volumes:
        - /home/osgdev/git/bookstore/db:/docker-entrypoint-initdb.d

  - name: "Launch tomcat container"
    docker:
      name: tomcat_container
      image: tomcat:9
      ports:
        - "12000:8080"
      volumes:
        - /home/osgdev/git/bookstore/target/:/usr/local/tomcat/webapps
      links:
        - mysql_container
